FROM node:12.16.1
EXPOSE 4000
WORKDIR /usr/src/app

#Following installation is ommited since in test environment, they're installed manually
#RUN npm install -g node-gyp jest

COPY . ./

# Create app directory
COPY package*.json ./
RUN npm install
