const EXAMINATION = 'examination';
const CONFIRMINATION = 'confirmation';
const PATIENT_CONFIRMINATION_EVENTS = 'CONFIRMINATION_PATIENT';

module.exports = {
  EXAMINATION,
  CONFIRMINATION,
  PATIENT_CONFIRMINATION_EVENTS,
};
