const EXAMINATION = 'examination';
const CONFIRMINATION = 'confirmation';
const RESERVATION_CONFIRM_EVENTS = 'CONFIRMINATION_PATIENT';

module.exports = {
  EXAMINATION,
  CONFIRMINATION,
  RESERVATION_CONFIRM_EVENTS,
};
