const ZALO_MESSAGE_SENT = 'ZALO_MESSAGE_SENT';
const ZALO_MESSAGE_RECEIVED = 'ZALO_MESSAGE_RECEIVED';
const ZALO_MESSAGE_CREATED = 'ZALO_MESSAGE_CREATED';

module.exports = {
  ZALO_MESSAGE_SENT,
  ZALO_MESSAGE_RECEIVED,
  ZALO_MESSAGE_CREATED,
};
